// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Killboard.Data.Models
{
    public partial class access_tokens
    {
        public int id { get; set; }
        public long char_id { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public DateTime date_added { get; set; }
        public DateTime expires_on { get; set; }

        public virtual characters char_ { get; set; }
    }
}