// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class alliances
    {
        public alliances()
        {
            attackers = new HashSet<attackers>();
            characters = new HashSet<characters>();
            corporations = new HashSet<corporations>();
            victims = new HashSet<victims>();
        }

        public string name { get; set; }
        public int? executor_corp_id { get; set; }
        public string ticker { get; set; }
        public int alliance_id { get; set; }

        public virtual ICollection<attackers> attackers { get; set; }
        public virtual ICollection<characters> characters { get; set; }
        public virtual ICollection<corporations> corporations { get; set; }
        public virtual ICollection<victims> victims { get; set; }
    }
}