// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class asteroid_belts
    {
        public int belt_id { get; set; }
        public string name { get; set; }
        public int planet_id { get; set; }
        public int position_id { get; set; }

        public virtual planets planet { get; set; }
        public virtual positions position { get; set; }
    }
}