// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class attackers
    {
        public long? char_id { get; set; }
        public int damage_done { get; set; }
        public bool final_blow { get; set; }
        public int ship_type_id { get; set; }
        public int weapon_type_id { get; set; }
        public int killmail_id { get; set; }
        public int? alliance_id { get; set; }
        public int? corporation_id { get; set; }
        public int attacker_id { get; set; }

        public virtual alliances alliance { get; set; }
        public virtual corporations corporation { get; set; }
        public virtual killmails killmail { get; set; }
        public virtual items ship_type { get; set; }
        public virtual items weapon_type { get; set; }
    }
}