// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Killboard.Data.Models
{
    public partial class character_scopes
    {
        public int char_id { get; set; }
        public int scope_id { get; set; }
        public bool approved { get; set; }

        public virtual characters char_ { get; set; }
        public virtual scopes scope_ { get; set; }
    }
}