// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class character_scopes
    {
        public long char_id { get; set; }
        public int scope_id { get; set; }
        public bool approved { get; set; }

        public virtual characters _char { get; set; }
        public virtual scopes scope { get; set; }
    }
}