// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class constellations
    {
        public constellations()
        {
            systems = new HashSet<systems>();
        }

        public int constellation_id { get; set; }
        public string name { get; set; }
        public int region_id { get; set; }
        public int position_id { get; set; }

        public virtual positions position_ { get; set; }
        public virtual regions region_ { get; set; }
        public virtual ICollection<systems> systems { get; set; }
    }
}