// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class dogma_attributes
    {
        public dogma_attributes()
        {
            item_attributes = new HashSet<item_attributes>();
        }

        public int attribute_id { get; set; }
        public double? default_value { get; set; }
        public string description { get; set; }
        public string display_name { get; set; }
        public bool? high_is_good { get; set; }
        public int? icon_id { get; set; }
        public string name { get; set; }
        public bool? published { get; set; }
        public bool? stackable { get; set; }
        public int? unit_id { get; set; }

        public virtual ICollection<item_attributes> item_attributes { get; set; }
    }
}