// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class dogma_modifiers
    {
        public int ref_effect_id { get; set; }
        public string domain { get; set; }
        public int? effect_id { get; set; }
        public string func { get; set; }
        public int modified_attribute_id { get; set; }
        public int modifying_attribute_id { get; set; }
        public int? _operator { get; set; }
        public int id { get; set; }

        public virtual dogma_effects ref_effect { get; set; }
    }
}