// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Killboard.Data.Models
{
    public partial class flags
    {
        public int flag_id { get; set; }
        public string name { get; set; }
    }
}