// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class groups
    {
        public groups()
        {
            items = new HashSet<items>();
        }

        public int group_id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public bool? published { get; set; }

        public virtual categories category_ { get; set; }
        public virtual ICollection<items> items { get; set; }
    }
}