// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class items
    {
        public items()
        {
            attackersship_type = new HashSet<attackers>();
            attackersweapon_type = new HashSet<attackers>();
            bloodlines = new HashSet<bloodlines>();
            item_attributes = new HashSet<item_attributes>();
            item_effects = new HashSet<item_effects>();
            planets = new HashSet<planets>();
            stargates = new HashSet<stargates>();
            stars = new HashSet<stars>();
            victims = new HashSet<victims>();
        }

        public int type_id { get; set; }
        public string name { get; set; }
        public float? capacity { get; set; }
        public string description { get; set; }
        public int group_id { get; set; }
        public int? icon_id { get; set; }
        public float? mass { get; set; }
        public int? portion_size { get; set; }
        public bool published { get; set; }
        public float? radius { get; set; }
        public float? volume { get; set; }

        public virtual groups group { get; set; }
        public virtual ICollection<attackers> attackersship_type { get; set; }
        public virtual ICollection<attackers> attackersweapon_type { get; set; }
        public virtual ICollection<bloodlines> bloodlines { get; set; }
        public virtual ICollection<item_attributes> item_attributes { get; set; }
        public virtual ICollection<item_effects> item_effects { get; set; }
        public virtual ICollection<planets> planets { get; set; }
        public virtual ICollection<stargates> stargates { get; set; }
        public virtual ICollection<stars> stars { get; set; }
        public virtual ICollection<victims> victims { get; set; }
    }
}