// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class items
    {
        public items()
        {
            attackersship_type_ = new HashSet<attackers>();
            attackersweapon_type_ = new HashSet<attackers>();
            bloodlines = new HashSet<bloodlines>();
            dropped_items = new HashSet<dropped_items>();
            planets = new HashSet<planets>();
            stargates = new HashSet<stargates>();
            stars = new HashSet<stars>();
            victims = new HashSet<victims>();
        }

        public int type_id { get; set; }
        public string name { get; set; }
        public float? capacity { get; set; }
        public string description { get; set; }
        public int group_id { get; set; }
        public int? icon_id { get; set; }
        public float? mass { get; set; }
        public int? portion_size { get; set; }
        public bool published { get; set; }
        public float? radius { get; set; }
        public float? volume { get; set; }

        public virtual groups group_ { get; set; }
        public virtual ICollection<attackers> attackersship_type_ { get; set; }
        public virtual ICollection<attackers> attackersweapon_type_ { get; set; }
        public virtual ICollection<bloodlines> bloodlines { get; set; }
        public virtual ICollection<dropped_items> dropped_items { get; set; }
        public virtual ICollection<planets> planets { get; set; }
        public virtual ICollection<stargates> stargates { get; set; }
        public virtual ICollection<stars> stars { get; set; }
        public virtual ICollection<victims> victims { get; set; }
    }
}