// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class item_effects
    {
        public int effect_id { get; set; }
        public bool is_default { get; set; }
        public int type_id { get; set; }

        public virtual dogma_effects effect { get; set; }
        public virtual items type { get; set; }
    }
}