// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class item_attributes
    {
        public int attribute_id { get; set; }
        public float value { get; set; }
        public int type_id { get; set; }

        public virtual dogma_attributes attribute { get; set; }
        public virtual items type { get; set; }
    }
}