// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class killmails
    {
        public killmails()
        {
            attackers = new HashSet<attackers>();
            dropped_items = new HashSet<dropped_items>();
            victims = new HashSet<victims>();
        }

        public string hash { get; set; }
        public DateTime? started_processing { get; set; }
        public DateTime? finished_processing { get; set; }
        public int killmail_id { get; set; }
        public DateTime? killmail_time { get; set; }
        public DateTime date_added { get; set; }
        public int? system_id { get; set; }

        public virtual systems system_ { get; set; }
        public virtual ICollection<attackers> attackers { get; set; }
        public virtual ICollection<dropped_items> dropped_items { get; set; }
        public virtual ICollection<victims> victims { get; set; }
    }
}