// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Killboard.Data.Models
{
    public partial class moons
    {
        public int moon_id { get; set; }
        public string name { get; set; }
        public int planet_id { get; set; }
        public int position_id { get; set; }

        public virtual planets planet_ { get; set; }
        public virtual positions position_ { get; set; }
    }
}