// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class planets
    {
        public planets()
        {
            asteroid_belts = new HashSet<asteroid_belts>();
            moons = new HashSet<moons>();
        }

        public int planet_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }
        public int item_type_id { get; set; }
        public int position_id { get; set; }

        public virtual items item_type_ { get; set; }
        public virtual positions position_ { get; set; }
        public virtual systems system_ { get; set; }
        public virtual ICollection<asteroid_belts> asteroid_belts { get; set; }
        public virtual ICollection<moons> moons { get; set; }
    }
}