// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Killboard.Data.Models
{
    public partial class procGetKillmailDetailsResult
    {
        public int KillmailId { get; set; }
        public string KillmailHash { get; set; }
        public long VictimCharacterId { get; set; }
        public string VictimName { get; set; }
        public int VictimCorporationId { get; set; }
        public int? VictimeAllianceId { get; set; }
        public string VictimCorporationName { get; set; }
        public string VictimAllianceName { get; set; }
        public int? Attackers { get; set; }
        public long FinalBlowCharId { get; set; }
        public string FinalBlowCharName { get; set; }
        public int FinalBlowCorporationId { get; set; }
        public int? FinalBlowAllianceId { get; set; }
        public string FinalBlowCorporationName { get; set; }
        public string FinalBlowAllianceName { get; set; }
        public int ShipTypeId { get; set; }
        public string ShipName { get; set; }
        public int SystemId { get; set; }
        public float SecurityStatus { get; set; }
        public string SystemName { get; set; }
        public int RegionId { get; set; }
        public string RegionName { get; set; }
        public DateTime? KillmailTime { get; set; }
    }
}
