// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Killboard.Data.Models
{
    public partial class procGetSystemsInJumpRangeResult
    {
        public int system_id { get; set; }
        public string name { get; set; }
        public float security_status { get; set; }
        public double? distance { get; set; }
    }
}
