// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Killboard.Data.Models
{
    public partial class races
    {
        public int race_id { get; set; }
        public string name { get; set; }
        public int alliance_id { get; set; }
        public string description { get; set; }
    }
}