// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Killboard.Data.Models
{
    public partial class reset_requests
    {
        public int request_id { get; set; }
        public int user_id { get; set; }
        public string hash { get; set; }
        public DateTime create_time { get; set; }
        public DateTime expire_time { get; set; }

        public virtual users user_ { get; set; }
    }
}