// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class scopes
    {
        public scopes()
        {
            character_scopes = new HashSet<character_scopes>();
        }

        public int scope_id { get; set; }
        public string scope_name { get; set; }
        public string description { get; set; }
        public int version { get; set; }
        public string full_name { get; set; }

        public virtual ICollection<character_scopes> character_scopes { get; set; }
    }
}