// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class stargates
    {
        public stargates()
        {
            Inversedestination_stargate_ = new HashSet<stargates>();
        }

        public int stargate_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }
        public int type_id { get; set; }
        public int destination_stargate_id { get; set; }
        public int position_id { get; set; }

        public virtual stargates destination_stargate_ { get; set; }
        public virtual positions position_ { get; set; }
        public virtual systems system_ { get; set; }
        public virtual items type_ { get; set; }
        public virtual ICollection<stargates> Inversedestination_stargate_ { get; set; }
    }
}