// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class stargates
    {
        public stargates()
        {
            Inversedestination_stargate = new HashSet<stargates>();
        }

        public int stargate_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }
        public int type_id { get; set; }
        public int destination_stargate_id { get; set; }
        public int position_id { get; set; }

        public virtual stargates destination_stargate { get; set; }
        public virtual positions position { get; set; }
        public virtual systems system { get; set; }
        public virtual items type { get; set; }
        public virtual ICollection<stargates> Inversedestination_stargate { get; set; }
    }
}