// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class stars
    {
        public int star_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }
        public int type_id { get; set; }
        public long? age { get; set; }
        public double luminosity { get; set; }
        public long? radius { get; set; }
        public string spectral_class { get; set; }
        public int? temperature { get; set; }

        public virtual systems system { get; set; }
        public virtual items type { get; set; }
    }
}