// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Killboard.Data.Models
{
    public partial class stations
    {
        public int station_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }

        public virtual systems system_ { get; set; }
    }
}