// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class systems
    {
        public systems()
        {
            factions = new HashSet<factions>();
            killmails = new HashSet<killmails>();
            planets = new HashSet<planets>();
            stargates = new HashSet<stargates>();
            stars = new HashSet<stars>();
            stations = new HashSet<stations>();
        }

        public int system_id { get; set; }
        public string name { get; set; }
        public int constellation_id { get; set; }
        public float security_status { get; set; }
        public string security_class { get; set; }
        public int position_id { get; set; }

        public virtual constellations constellation { get; set; }
        public virtual positions position { get; set; }
        public virtual ICollection<factions> factions { get; set; }
        public virtual ICollection<killmails> killmails { get; set; }
        public virtual ICollection<planets> planets { get; set; }
        public virtual ICollection<stargates> stargates { get; set; }
        public virtual ICollection<stars> stars { get; set; }
        public virtual ICollection<stations> stations { get; set; }
    }
}