// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Killboard.Data.Models
{
    public partial class users
    {
        public users()
        {
            characters = new HashSet<characters>();
            reset_requests = new HashSet<reset_requests>();
        }

        public int user_id { get; set; }
        public string username { get; set; }
        public string hash { get; set; }
        public DateTime create_time { get; set; }
        public string create_ip { get; set; }
        public DateTime? modified_time { get; set; }
        public string modified_ip { get; set; }
        public string email { get; set; }
        public byte[] salt { get; set; }

        public virtual ICollection<characters> characters { get; set; }
        public virtual ICollection<reset_requests> reset_requests { get; set; }
    }
}